services:
  # Dozzle - Real-time Docker Log Viewer
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    security_opt:
      - no-new-privileges:true
    restart: always
    profiles: ["apps", "all"]
    networks:
      - default
      - socket_proxy
    #ports:
    #  - "$DOZZLE_PORT:8080"
    environment:
      - DOZZLE_LEVEL=info
      # - DOZZLE_TAILSIZE=300 # throws errors?!
      - DOZZLE_FILTER="status=running"
      # - DOZZLE_FILTER="label=log_me" # limits logs displayed to containers with this label
      - DOCKER_HOST=$DOCKER_HOST
    #. volumes:
    #  - /var/run/docker.sock:/var/run/docker.sock # Use Docker Socket Proxy instead for improved security
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.dozzle-rtr.entrypoints=websecure-internal"
      - "traefik.http.routers.dozzle-rtr.rule=Host(`dozzle.$DOMAINNAME_1`)"
      # Middlewares
      - "traefik.http.routers.dozzle-rtr.middlewares=chain-no-auth@file"
      # HTTP Services
      - "traefik.http.routers.dozzle-rtr.service=dozzle-svc"
      - "traefik.http.services.dozzle-svc.loadbalancer.server.port=8080"

      # Homepage
      - "homepage.group=Core"
      - "homepage.name=Dozzle"
      - "homepage.href=http://dozzle.$DOMAINNAME_1/"
      - "homepage.description=Real-time Docker Log Viewer"
