services:
  # Tdarr node
  tdarr-node:
    image: ghcr.io/haveagitgat/tdarr_node:latest
    container_name: tdarr-node
    security_opt:
      - no-new-privileges:true
    restart: "no"
    profiles: ["media", "starr", "all"]
    networks:
      - t3_proxy
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - $APPDATADIR/tdarr/configs:/app/configs
      - $APPDATADIR/tdarr/logs:/app/logs
      - $MEDIADIR1:/media
      - $DOWNLOADSDIR/transcode/tdarr:/temp
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
      - UMASK_SET=002
      - nodeID=Internal-node
#      - nodeIP=tdarr-node
#      - nodePort=8267
      - serverIP=tdarr
      - serverPort=8266
      - nodeType=mapped
      - transcodecpuWorkers=2
      - pollInterval=2000
